### ISSUE TITLE
First argument must be a string or Buffer

### ISSUE THREAD

**Issue by DaleLJefferson** [bugsnag/bugsnag-sourcemaps#1]
If you use the overwrite option (as per the readme)

```
upload({
    ...,
    overwrite: true
})
```

You get the following error from request

```
_http_outgoing.js:456
    throw new TypeError('First argument must be a string or Buffer');
    ^

TypeError: First argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:456:11)
```

As a work around you can change overwrite to a string `overwrite: 'true'`

**Comment by jmshal** [comment]
Thanks for the report, @DaleJefferson. I was literally just investigating this issue, so I appreciate you locating the cause. A fix will be pushed shortly.

**Comment by DaleLJefferson** [comment]
Thanks for the prompt response, I'm using this with React Native and it seems to work nicely. Thanks for open sourcing this.
