### ISSUE TITLE
npm ERR! missing script: bugsnag-sourcemaps

### ISSUE THREAD

**Issue by udfalkso** [bugsnag/bugsnag-sourcemaps#14]
After doing an npm install I try to do:
`npm run bugsnag-sourcemaps` with the various arguments after -- and I just get this error

```
$ npm run bugsnag-sourcemaps -- --api-key xxxxxxxxxxx --minified-url 'main.jsbundle' --source-map ios/main.jsbundle.map --minified-file ios/main.jsbundle --overwrite --upload-sources 
npm ERR! missing script: bugsnag-sourcemaps

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/udi/.npm/_logs/2017-08-08T20_33_45_304Z-debug.log
```

```
$ npm -v
5.3.0
```

```
$ ls node_modules/bugsnag-sourcemaps/
CHANGELOG.md  LICENSE       README.md     cli.js        index.js      node_modules/ package.json  
```

What am I missing?  Thanks

**Comment by kattrali** [comment]
Thanks for the report, @udfalkso. I can confirm the same behavior. I think `npm run` is just for items listed in scripts, though it does resolve bin stubs. So if you add `bugsnag-sourcemaps` to your `package.json`, everything just works:

```json
{
     "scripts" : {
        "bugsnag-sourcemaps": "bugsnag-sourcemaps"
    }
}
```

Maybe this behavior changed in npm? [Here is the `npm run` docs](https://docs.npmjs.com/cli/run-script). I also noticed that `yarn run` handles this case without needing a script declared, so maybe there's some confusion there too.

**Comment by udfalkso** [comment]
Thanks @kattrali 

`yarn run bugsnag-sourcemaps` works.  The README should probably indicate to try this if npm run fails.  Or to add bugsnag-sourcemaps in scripts.
