### ISSUE TITLE
React native example?

### ISSUE THREAD

**Issue by wootwoot1234** [bugsnag/bugsnag-sourcemaps#15]
Do you have an example of how to use this with react native?  

For example, I'm stuck on what to supply for the `--minified-url`.

Thanks!

**Comment by bengourley** [comment]
As per #16, documentation is located here: https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/

**Comment by RameshDev92** [comment]
Hi @wootwoot1234 did u find out what to supply for --minified-url.

**Comment by wootwoot1234** [comment]
No, sorry.

**Comment by james2m** [comment]
> As per #16, documentation is located here: https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/

This is a totally unhelpful response and the ticket should not have been closed. The documentation doesn't describe --minified-url whatsoever in relation to react-native.

**Comment by xljones** [comment]
Hi @james2m, the value given for `--minified-url` is part of what we use to match an event (report) to a sourcemap, along with the Application Version or Code Bundle ID.

Please note that `bugsnag-sourcemaps` should only be used on a React Native project with Hermes. If you are using a regular React Native project, you should be using `curl`: https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#uploading-source-maps-to-bugsnag

The first in-project frame of your stacktrace will have a file reported. The frame will look something like this in Bugsnag:
```
index.android.bundle:1:20157 anonymous
```
In this case, the `minified-url` should be set to `index.android.bundle`

When using CodePush **_and_** Hermes on Android, your frame will look something like this:
```
/data/user/0/<application_name>/files/CodePush/<hashed_key>/CodePush/index.android.bundle:1:236003 onPress
```
So to address this, we simply add the `--add-wildcard-prefix` along with the same `minified-url` as above: https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#uploading-hermes-source-maps

If you would like some more project specific help and advice, please get in touch with us at support@bugsnag.com with more details of what you're trying to achieve! 😄
