### ISSUE TITLE
code splitting and uploading all the source maps

### ISSUE THREAD

**Issue by amanthegreatone** [bugsnag/bugsnag-sourcemaps#21]
Hi,

In my react app I am using code splitting ([react-loadable](https://github.com/jamiebuilds/react-loadable)) to reduce the bundle size and serve them on demand whenever the respective route is loaded. Using this technique I am getting about 53 chunks and a main file (.js and .map). 
How can I upload all these source maps to identify the error stack trace correctly.

regards
Aman

**Comment by bengourley** [comment]
Some suggestions we made over on this issue: https://github.com/bugsnag/bugsnag-js/issues/339

Please reopen if a bug or defect is preventing you from succeeding in this! Cheers
