### ISSUE TITLE
Sourcemaps overwritten

### ISSUE THREAD

**Issue by chrisnovak** [bugsnag/bugsnag-sourcemaps#23]
### Expected behavior
Sourcemaps are not overwritten by default.

### Observed behavior
Sourcemaps are overwritten when using the CLI—regardless of whether `--overwrite false` is included or not.

### Steps to reproduce
``bugsnag-sourcemaps --api-key XXXXX --app-version 173 --source-map bundle/android-release.bundle.map --minified-file bundle/android-release.bundle --minified-url index.android.bundle --upload-sources --overwrite false``

or 

 ``bugsnag-sourcemaps --api-key XXXXX --app-version 173 --source-map bundle/android-release.bundle.map --minified-file bundle/android-release.bundle --minified-url index.android.bundle --upload-sources``

### Version
1.0.3

### Additional Info
We've also confirmed that the sourcemaps are being overwritten in the Bugsnag UI.

**Comment by bengourley** [comment]
Hi @chrisnovak, thanks for filing this issue. We managed to reproduce the issue, and I'm working on a fix over in #24. I'll keep you updated.

**Comment by chrisnovak** [comment]
Thank you for fixing this quickly! Confirmed working on 04e2846.

**Comment by bengourley** [comment]
Great! Thanks for reporting it. This is now published in v1.0.4.
