### ISSUE TITLE
Empty app version sent when none specified

### ISSUE THREAD

**Issue by JacobEvelyn** [bugsnag/bugsnag-sourcemaps#29]
### Expected behavior

I have no app version specified in my `package.json` file and I don't use the `--app-version` flag with this CLI. I'd expect the app version of my uploaded sourcemap to thus be `null`.

### Observed behavior

However, Bugsnag support tells me that it's getting uploaded as an empty string (`""`), which is preventing it from working because my errors have no version (`null`) and Bugsnag treats these as not matching.

### Steps to reproduce

Use the CLI to upload a sourcemap. Don't specify a `-v` or `--app-version` flag, and don't have a version set in your project's `package.json`.

### Version

1.0.4

**Comment by bengourley** [comment]
Fixed via #30 in v1.0.6.

**Comment by JacobEvelyn** [comment]
Looks like it's working in 1.0.6, thanks!
