### ISSUE TITLE
feature request: environemnt varibles support

### ISSUE THREAD

**Issue by punksta** [bugsnag/bugsnag-sourcemaps#34]
Sometimes it's easier to pass params using environment variables.  Specially in ci scripts. 

### Expected behavior
you can pass params using environment variables. 

### Observed behavior
you can pass params only using cli argument

**Comment by bengourley** [comment]
It's pretty simple to pass them through yourself, e.g.

```sh
export BUGSNAG_API_KEY=XXXXXXXXXX
export APP_VERSION=1.2.3

bugsnag-sourcemaps upload \
  --api-key $BUGSNAG_API_KEY \
  --app-version $APP_VERSION \
  --source-map path/to/main.js.map \
  --minified-file path/to/main.js
```

**Comment by punksta** [comment]
@bengourley in my case it's not possible. gitlab ci has problems with multi-line scripts

**Comment by bengourley** [comment]
I just did that so it looked nice – you can put it on one line:

```sh
bugsnag-sourcemaps upload --api-key $BUGSNAG_API_KEY --app-version $APP_VERSION --source-map path/to/main.js.map --minified-file path/to/main.js
```
