### ISSUE TITLE
Upload is exceeding maxFields

### ISSUE THREAD

**Issue by fossage** [bugsnag/bugsnag-sourcemaps#4]
I am getting the following error when uploading source maps.

```sh
[18:12:17]: ▸ [18:12:17] Uploading sourcemaps [started]
[18:12:46]: ▸ [18:12:46] Uploading sourcemaps [failed]
[18:12:46]: ▸ [18:12:46] → maxFields 1000 exceeded.
```

I am using the following commands to initiate the upload:

```sh
react-native bundle --platform ios --dev false --entry-file index.ios.js --bundle-output /tmp/main.jsbundle --sourcemap-output /tmp/main.jsbundle.map

bugsnag-sourcemaps upload --api-key #{bugsnag_key} --source-map /tmp/main.jsbundle.map --strip-project-root --minified-file /tmp/main.jsbundle --minified-url main.jsbundle --upload-sources
```

Is this possibly an issue on the server side needing it's maxFields value bumped up for multi-part forms, or is there something obvious that I am overlooking?

**Comment by kattrali** [comment]
Thanks for the report, @fossage. Most likely this is an issue with the plugin itself, and I'm looking into where `maxFields` could be coming from. 🤔

**Comment by fossage** [comment]
Just FYI, I was able to get it to work using curl doing something like this:

```sh
curl https://upload.bugsnag.com/ -F apiKey=#{bugsnag_key} -F overwrite=true -F appVersion=1.0 -F sourceMap=@/tmp/main.jsbundle.map -F minifiedFile=@/tmp/main.jsbundle -F minifiedUrl=\"main.jsbundle\"
```

**Comment by kattrali** [comment]
Thanks. So it works when not uploading source files, then. So does it work when you try (excluding `--upload-sources`):

```
bugsnag-sourcemaps upload --api-key #{bugsnag_key} \
  --source-map /tmp/main.jsbundle.map \
  --strip-project-root \
  --minified-file /tmp/main.jsbundle \
  --minified-url main.jsbundle
```

Maybe it can be narrowed down to payload size somehow.

**Comment by kattrali** [comment]
Ah! I think I've located the issue. I'll post an update with the resolution soon.

**Comment by fossage** [comment]
Thanks!  Sorry I didn't get a chance to try what you were asking.  Got a bit sidetracked there for a while.

**Comment by kattrali** [comment]
We've raised the file limit so you can use `--upload-sources` and this should be resolved.
