### ISSUE TITLE
Retry on timeouts and other socket errors deletes temp files before retry

### ISSUE THREAD

**Issue by jeffdeliso** [bugsnag/bugsnag-sourcemaps#44]
When retrying on timeouts and other socket errors the temporary files are deleted before the other attempts occur resulting in the attached error.

### Version
1.2.1

### Additional information
![Screen Shot 2019-07-15 at 10 24 02 AM](https://user-images.githubusercontent.com/4982876/61224623-e66e6d00-a6ec-11e9-9dc2-9d9e7556fec2.png)

**Comment by mattdyoung** [comment]
Hi @jeffdeliso 

Thanks for the report, which does look to be a bug in our tool. We're just picking up the issue now to work on a fix.

**Comment by bengourley** [comment]
Initially I thought this would be possible, but after investigating it I can't see a sequence of events where the tmpdir is removed before a retry occurs.

- how often is this happenening for you?
- is it possible that the disk is near full and the tmp directory is being cleaned up by the system (or some other process)?

If you can reliably reproduce this that would really help us fix the potential problem. The [integration tests model some network conditions](https://github.com/bugsnag/bugsnag-sourcemaps/blob/95acc1142a16809f9f56228c4f5692e3c671159a/test/integration.test.js#L125-L152) where a request is retried a number of times before it eventually gets through.

**Comment by abigailbramble** [comment]
Closing as we have not been able to reproduce.
