### ISSUE TITLE
Is app version code be supported

### ISSUE THREAD

**Issue by jasonhaihuang** [bugsnag/bugsnag-sourcemaps#47]
### Expected behavior
The upload of the source map can specify app version code(A.K.A build number) like the curl command does before.

### Observed behavior
There is no parameter for app version code, tried app-version-code, versionCode, version-code, but all come back with 409 error.

By adding --overwrite can solve this issue, but there will be only one source map for each app version. 

### Steps to reproduce
Upload RN0.60 source map with same app version name, the first upload 

### Version
bugsnag-sourcemaps: 1.2.1
React Native: 0.60.5

### Additional information
*[Insert any additional information]*

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by mattdyoung** [comment]
Hi @jasonhaihuang 

Are you using Hermes on Android with React Native and trying to upload the relevant source maps?

For apps **_not_** using Hermes we'd recommend following the instructions here to upload the source maps using `curl`:
https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#uploading-source-maps-to-bugsnag

For apps using Hermes, you should follow the instructions here to upload source maps using `bugsnag-sourcemaps`:
https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#uploading-hermes-source-maps

For `bugsnag-sourcemaps` can you can specify either the app version or the version code as the `--app-version` parameter and if the value specified matches either the `version` or `versionCode` field shown on the App tab of your error, the source map will be applied.

**Comment by tberman** [comment]
I appreciate closing this but its not actually a solution.

We often distribute multiple test versions of our app via testflight where they have the same version but very different js bundles.

Supporting the fully qualified version information is important to be able to use bugsnag properly.

**Comment by xljones** [comment]
Hey @tberman, we do support the use of `appVersion`, `appVersionCode`, or `appVersionBundle` if you `POST` the sourcemaps to https://upload.bugsnag.com/react-native-source-map. 

See https://docs.bugsnag.com/api/rn-source-map-upload/#uploading-source-maps for more details

So long as the supplied equivalent values in the `App` tab of your event matches the sourcemaps you've uploaded, we'll find the appropriate sourcemap.

**Comment by tberman** [comment]
Great. Just to clarify, if I provide via the POST api both the appversion and the versionCode/bundleVersion the source map in question will match using both versions, and I will be able to have more than one source map up per appVersion (presuming unique pairs)?

**Comment by xljones** [comment]
That's correct! For full disclosure, on React Native sourcemaps, we match in the following order of precedence:
1. `codeBundleId`
2. `appVersion` AND `versionCode` OR `bundleVersion`
3. `versionCode`
4. `appVersion`

You should give an `appVersion` and one of the following `versionCode` OR `bundleVersion`, these are synonymous, but used to highlight the difference between iOS and Android. Just pipe in `appVersion` and `versionCode`, and we'll make a match on both of these 😄

**Comment by tberman** [comment]
Great, thanks!

Any reason this code hasn't been updated to support that?

**Comment by xljones** [comment]
@tberman the upload endpoint does support `versionCode` and `bundleVersion`, I have updated my comment above to reflect this. I was attempting to make it as clear as possible by giving a direct example, but this may have caused the confusion.

**Comment by tberman** [comment]
> @tberman the upload endpoint does support `versionCode` and `bundleVersion`, I have updated my comment above to reflect this. I was attempting to make it as clear as possible by giving a direct example, but this may have caused the confusion.

Sorry, confusion was created by my response! I mean 'this code' as in, `bugsnag-sourcemaps`.

We are happy to use the POST endpoint, but its confusing that this is the officially recommended solution and doesn't support it!

Also, it'd be great if the react-native docs included the comment you made really clearly to make it easier to understand what bugsnag will do with sourcemaps!

**Comment by mohsinulhaq** [comment]
@xander-jones for Android apps using Hermes, we can't use the POST endpoint, we have no other option other than using this package, how do I specify version code here?

**Comment by xljones** [comment]
Hey @mohsinulhaq, `bugsnag-sourcemaps` does not support `versionCode` (or `bundleVersion`). You should use `codeBundleId` here if you need a unique ID if you have more than one sourcemap / release per `appVersion`.

**Comment by mohsinulhaq** [comment]
But will that not affect anything in the way Bugsnag behaves? Because of the fact that `codeBundleId` is for Codepush?

**Comment by xljones** [comment]
No, it's okay to use 😄 . If we see a `codeBundleId`, we use this as the primary lookup, if you don't provide it, we flow down to the next item in the list above, which would be `appVersion` in that case.

**Comment by mohsinulhaq** [comment]
oh ok, got it, thanks!

**Comment by mohsinulhaq** [comment]
![image](https://user-images.githubusercontent.com/7688231/89791941-8f320a80-db41-11ea-8519-e8fd9a25f400.png)
@xander-jones I just uploaded the sourcemap using the version code as codeBundleId, now the bugsnag dashboard doesn't even show the appVersion

**Comment by mattdyoung** [comment]
@mohsinulhaq - sorry for the delay. When using `bugsnag-sourcemaps` if you specify a `--code-bundle-id` this alone is used to match the sourcemap so would need to be unique across all your builds. If you specify a `--app-version` this can be set to either your app's `appVersion` or `versionCode`:
https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#generating-and-uploading-hermes-source-maps

If you're still having issues getting the source maps to apply I'd suggest writing in to support@bugsnag.com with a link to an error that's failed to map so we can analyze what's not matching and advise.

**Comment by chrisnovak** [comment]
We've been using codeBundleId for years due to this issue, and it's still a gross workaround. Any reason why this isn't supported with this tool? Seems like it'd be fairly straightforward to implement.

**Comment by xljones** [comment]
Hey @chrisnovak, we're releasing a new tool soon which will take care of this (amongst a bunch of other new features too). It's undergoing testing at the moment, so all going well expect to see it drop in the next few weeks. In the interest of keeping this thread updated, I've reopened this issue.

**Comment by xljones** [comment]
Our new source maps CLI tool has been released: https://github.com/bugsnag/bugsnag-source-maps which supports app bundle version metadata, amongst a whole bunch of other ease-of-use features.

Using `@bugsnag/source-maps` with:
* Browser projects: https://docs.bugsnag.com/build-integrations/js/source-maps-browser/
* Node.js projects: https://docs.bugsnag.com/build-integrations/js/source-maps-node/
* React Native projects: https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/

_Note_: You should continue to use `codeBunldeId` if you're using CodePush as the internal JS bundle needs a seperate identifier to the application binary.
