### ISSUE TITLE
Can't upload sourcemaps when using codepush

### ISSUE THREAD

**Issue by grundmanise** [bugsnag/bugsnag-sourcemaps#5]
The command from here: https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/#how-should-i-upload-source-maps-if-i-39-m-using-codepush

```
$ bugsnag-sourcemaps upload \
     --api-key <PROJECT API KEY> \
     --code-bundle-id 1.0-123 \
     --source-map <path to source map> \
     --minified-file <path to bundle> \
     --upload-sources \
     --add-wildcard-prefix
```

Does not do anything. No errors and no success messages. In `Settings >Projects > Uploaded source maps` - I don't see that sourcemaps are uploaded. I managed to upload sourcemaps with this command:

`bugsnag-sourcemaps upload --api-key XXXX --app-version 2.7 --code-bundle-id 2.7 --minified-url main.jsbundle --source-map ./dist/codepush/main.jsbundle.map --minified-file ./dist/codepush/main.jsbundle --upload-sources --add-wildcard-prefix`

In `Settings >Projects > Uploaded source maps` I can see that sourcemaps are uploaded but the `APP VERSION` is not applied "-" thus stacktraces are not readable.

What am I doing wrong?

**Comment by jmshal** [comment]
Hi @grundmanise, I have been able to replicate this issue. Please, would you be able to try again with the latest release candidate, and let me know how it goes?

```sh
$ npm install -g bugsnag-sourcemaps@1.0.0-rc.3
```

Cheers!

**Comment by grundmanise** [comment]
@jmshal Thanks for support, but still no luck..  I get:  `Bad Request (400) - missing required param: minifiedUrl` when I use the command from the docs, if I include `--minified-url` I can upload sourcemaps, but the stacktrace is still obfuscated. Also when adding `--app-version` it is not applied.

![capture](https://user-images.githubusercontent.com/19417672/27264363-78fdc1be-5485-11e7-86ae-38b905e38d54.JPG)
![capture2](https://user-images.githubusercontent.com/19417672/27264364-7ad701da-5485-11e7-804d-52b114f6555e.JPG)
![capture3](https://user-images.githubusercontent.com/19417672/27264366-7c3d748c-5485-11e7-8bae-0eed92681524.JPG)

**Comment by jmshal** [comment]
From my understanding, errors that contain a `codeBundleId` only take into account the `codeBundleId` and not the `appVersion`.

If you manually try and send both `appVersion` and `codeBundleId` to the sourcemaps endpoint Bugsnag responds with the following error: `only one of 'appVersion' and 'codeBundleId' can be provided`. I believe you need to call `bugsnag-sourcemaps` twice, one for standard bundles and another for CodePush.

Can you also confirm that you're using the `--add-wildcard-prefix` flag when uploading your CodePush bundle? More info can be found here https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/#how-should-i-upload-source-maps-if-i-39-m-using-codepush.

I hope that helps.

**Comment by kattrali** [comment]
@grundmanise I'm taking a shot in the dark here somewhat, but does it work if you set `--minified-url` as `*/main.jsbundle`? If so, it might mean that we need to add a tweak to the `--add-wildcard-prefix` behaviour.

**Comment by grundmanise** [comment]
@kattrali Thank you very much! Your solution works!

`bugsnag-sourcemaps upload --api-key XXXX --code-bundle-id 2.7 --minified-url */main.jsbundle --source-map ./dist/codepush/main.jsbundle.map --minified-file ./dist/codepush/main.jsbundle --upload-sources --strip-project-root  --overwrite`
