### ISSUE TITLE
Options not explained consistently

### ISSUE THREAD

**Issue by googol7** [bugsnag/bugsnag-sourcemaps#51]
### Expected behavior
The options should be explained consistently.

### Observed behavior
`bugsnag-sourcemaps --help` returns options that are not explained in the [README](https://github.com/bugsnag/bugsnag-sourcemaps/blob/master/README.md):

```
-n, --upload-node-modules  Upload dependency files referenced by the source map
```

In the [README](https://github.com/bugsnag/bugsnag-sourcemaps/blob/master/README.md) there’s an option not being offered by bugsnag-sourcemaps 1.2.2 anymore (?):
```
-t, --strip-project-root   Strip the root path from file paths in the source map
```

[Here](https://docs.bugsnag.com/build-integrations/js/#source-map-uploader) `-add-wildcard-prefix` and `--upload-node-modules` are missing.

### Version
1.2.2

**Comment by mattdyoung** [comment]
Hi @googol7 

Thanks for pointing this out. We'll align the docs, readme and help to ensure all are consistent with the latest version.

**Comment by googol7** [comment]
@mattdyoung a real life example would also be good. The option `--add-wildcard-prefix` is always needed because otherwise Bugsnag won’t find the sourcemaps - correct?!

I'm using `create-react-app` and `yarn build` and this creates a directory `/build`. When releasing to production I don’t want to have that `/build` path in my URL of course - so I use the option `--project-root build`. On Bugsnag under **Manage JavaScript source maps** I see:

`static/js/5.445709ee.chunk.js`

So the wildcard is missing at the beginning of the URL. I have to add that with another option

`--add-wildcard-prefix "http*://*/"`

Bugsnag automatically changes this wildcard to:

`*static/js/5.445709ee.chunk.js`

So IMHO a real world example would be:

```
./node_modules/.bin/bugsnag-sourcemaps upload --api-key YOUR_API_KEY_HERE \
   --app-version THE_VERSION_HERE \
   --directory \
   --project-root build \
   --add-wildcard-prefix "http*://*/" \
   --overwrite
```

**Comment by mattdyoung** [comment]
Note that the `--add-wildcard-prefix` doesn't take any parameters. You just specify the option and it prepends `*` on any minified URL specified.

The options are explained in more detail in the docs here:
https://docs.bugsnag.com/build-integrations/js/#uploading-source-maps

For a browser bundle you should upload like this:
```
bugsnag-sourcemaps upload --api-key YOUR_API_KEY_HERE \
    --app-version 1.2.3 \
    --minified-url 'http://example.com/assets/example.min.js' \
    --source-map path/to/example.js.map \
    --minified-file path/to/example.min.js
```
and you'd only need to specify `--add-wildcard-prefix` if you're serving the same Javascript from multiple domains and want the source map to match all of them:
```
bugsnag-sourcemaps upload --api-key YOUR_API_KEY_HERE \
    --app-version 1.2.3 \
    --minified-url '/assets/example.min.js' \
    --source-map path/to/example.js.map \
    --minified-file path/to/example.min.js \
    --add-wildcard-prefix
```

For a Node.js project you can use the directory mode to upload all generated bundles and source maps in your build:
```
bugsnag-sourcemaps upload --api-key YOUR_API_KEY_HERE \
    --app-version 1.2.3 \
    --directory
```
and you'd only need to specify specify `--add-wildcard-prefix` if for some reason the paths shown in your stacktraces didn't match the relative path from the project root determined by the directory option:
```
bugsnag-sourcemaps upload --api-key YOUR_API_KEY_HERE \
    --app-version 1.2.3 \
    --directory \
    --add-wildcard-prefix
```

**Comment by googol7** [comment]
@mattdyoung Thanks for pointing this out! `--add-wildcard-prefix` isn’t mentioned in the online docs yet.

Nice examples! Would be perfect to see them in the docs. I would also describe the `--add-wildcard-prefix` differently:

**OLD:** Insert a wildcard prefix when stripping root path
**NEW:** Insert a wildcard prefix when stripping root path with option `-r, --project-root`

Why would I use `--add-wildcard-prefix` when using multiple domains?
If I upload it with `--minified-url '/assets/example.min.js'` then Bugsnag doesn't restrict it to a certain domain, correct? Only if I would provide a domain in `--minified-url 'http://example.com/assets/example.min.js'` then it would be restricted to a domain - correct?

I don’t understand what this option really does?
`-t, --strip-project-root   Strip the root path from file paths in the source map`

In my case I use nice URLs (like everybody else I guess ;-) so the URLs look like this:

`/ship/42/crew/`

So I have to define `--add-wildcard-prefix` because otherwise Bugsnag would look for the path `/ship/42/crew/static/js/5.445709ee.chunk.js`
instead of
`/static/js/5.445709ee.chunk.js`

**Comment by mattdyoung** [comment]
Hi @googol7 

If you're uploading a single source map the `--add-wildcard-prefix` option is equivalent to supplying a `*` in front of the minified URL so isn't really required as you can just do this:
```
--minified-url '*/assets/example.min.js'
```

The `--strip-project-root` option strips the project root from the file paths in the source map, provided you also supplied the `--project-root` option to specify a project root.

E.g. if the paths in your source map are something like `/path/to/my/assets/example.min.js` you could specify:
```
--project-root /path/to/my \
--strip-project-root
```
to ensure that that the source map uploaded to Bugsnag only contains file paths like `/assets/example.min.js` so that they match the stracktraces reported in your errors.

If you're having specific issues getting source maps to apply correctly I'd recommend contacting support@bugsnag.com with details of how you're uploading and a link to an example in your dashboard of an error which hasn't mapped correctly and we can advise on specifics.

**Comment by googol7** [comment]
@mattdyoung Thanks for your comments. This makes it a lot clearer.

I have only one remaining question: When I upload multiple source maps with `bugsnag-sourcemaps` I use `--directory` and can’t provide `--minified-url`. How will Bugsnag find the corresponding source map if you don’t provide `--add-wildcard-prefix` as in the example in the [README](https://github.com/bugsnag/bugsnag-sourcemaps/blob/master/README.md#command-line-usage)?

**Comment by mattdyoung** [comment]
The `--directory` option is currently only supported for Node.js projects, not browser Javascript:
https://docs.bugsnag.com/build-integrations/js/#uploading-source-maps

This scans the project root for source maps, uploading them all including their relative paths.

For a Node.js project, this relative directory structure _may_ match the paths reported in the stacktrace, but if those are prefixed with a different path you would need to use `--add-wildcard-prefix` to ensure these match.
