### ISSUE TITLE
 bugsnag-sourcemaps slow

### ISSUE THREAD

**Issue by lukas1994** [bugsnag/bugsnag-sourcemaps#57]
I'm running
```
#!/bin/bash
API_KEY=XXX
bugsnag-sourcemaps upload --api-key $API_KEY \
    --app-version $1 \
    --overwrite=true \
    --directory
```
and it takes ~20sec. Is there a way to speed this up? It's part of my docker build process so it'd be great to make this faster :)

**Comment by mattdyoung** [comment]
Hi @lukas1994 

Using the `--directory` option recursively searches the build output for source maps to upload. If you have another way to generate a list of the source maps output by you build it may be quicker to iterate over that list and upload them individually:
```
bugsnag-sourcemaps upload --api-key $API_KEY \
    --app-version 1.2.3 \
    --minified-url '*/example.min.js' \
    --source-map path/to/example.js.map \
    --minified-file path/to/example.min.js
```

Why the `--overwrite=true` flag? That should only be required if you are uploading more than once for the same app-version. If that's the case there may be a saving if you can detect when you've already uploaded the source maps for that app-version.

**Comment by lukas1994** [comment]
I can remove overwrite=true, I think I needed it back in the day.
Can I upload a list of .map files with one command?

**Comment by mattdyoung** [comment]
No, you'd need to call bugsnag-sourcemaps once for each file with that syntax, but depending how many source maps you have vs how big your directory structure is it may be quicker.

**Comment by lukas1994** [comment]
Ok I’ll try that. Thanks :)
