### ISSUE TITLE
Upload a directory with a cdn host url

### ISSUE THREAD

**Issue by tleunen** [bugsnag/bugsnag-sourcemaps#58]
It doesn't look possible to upload a directory with a custom CDN host url, am I right?
The reason being that the `minifiedUrl` becomes computed from the `projectRoot` without any way to really customize it.
Am I missing anything?

https://github.com/bugsnag/bugsnag-sourcemaps/blob/7079744beb65b1522d8d73cfc5910b4a7319fa72/index.js#L93

**Comment by johnkiely1** [comment]
Hi @tleunen.

I assume you are attempting to use the `--directory` option with the bugsnag-sourcemaps tool to upload multiple sourcemaps at once. This only works for node.js and will not work for frontend javascript projects.https://docs.bugsnag.com/build-integrations/js/#cli-source-maps.

Could you clarify what you are trying to achieve and how you are using the bugsnag-sourcemaps tool?

Thanks

**Comment by tleunen** [comment]
Hi @johnkiely1 - Indeed, I wanted to see if/how I could use the `directory` option to make my script simpler since a frontend JS project now can have quite a few bundles.
Because it seems it forces consumers to "rebuild" a script which does mostly what the `uploadMany` does, which is calling `uploadOne` with the right options.

**Comment by mattdyoung** [comment]
Hi @tleunen 

That isn't currently supported with `bugsnag-sourcemaps`. What build tool are you using? If you're using webpack our [webpack plugin](https://docs.bugsnag.com/build-integrations/webpack/) does support uploading multiple chunks/bundles so may be a better option.

**Comment by xljones** [comment]
Closing for now pending further information on build tool.
