### ISSUE TITLE
Bugsnag showing url of minified files instead of upload sourcemap files.

### ISSUE THREAD

**Issue by harsimerkaur** [bugsnag/bugsnag-sourcemaps#61]
### Describe the bug
I have used upload API of bugsnag to upload sourcemaps on bugsnags for my react app and then I am deleting the sourcemaps from my host.
After doing this when I checked bugsnag sourcemaps setting it is showing me minified files URLs in  "Source URL" column.

![image](https://user-images.githubusercontent.com/38556673/98810823-c87e5d00-2445-11eb-97e5-1abcb6fc8740.png)

I am getting a message: 

> Source mapping failed:
> A source map could not be found
> Could not find original source file and line numbers because the source map could not be downloaded from https://hostname/minifiedFileName.js.map. Ensure that your source map is accessible from our servers or upload them to us. (Note that events are not reprocessed after source maps are uploaded.)
> 

This is because after uploading I am deleting sourcemaps from build. I am assuming with upload API sourcemaps are uploaded to bugsnag and we don't need to keep sourcemaps at our host.

I am not understanding what step am I missing in uploading sourcemaps to bugsnag.

### Environment
node version > 10
"@bugsnag/js": "^7.5.1",
"@bugsnag/plugin-react": "^7.3.5",

### Example code snippet 

I have created a file process-bugsnag-sourcemaps.js
```

const { upload } = require('bugsnag-sourcemaps');
const reportBuild = require('bugsnag-build-reporter');
const glob = require('glob');
const fs = require('fs');

function uploadSourceMap(sourceMap) {
  const minifiedFile = sourceMap.replace('.map', '');
  const minifiedFileServerPath = `${minifiedFile.split('/')[2]}/${
    minifiedFile.split('/')[3]
  }/${minifiedFile.split('/')[4]}`;

  return upload({
    apiKey: config.get('BUGSNAG_API_KEY'),
    appVersion,
    overwrite: true,
    minifiedUrl: `${config.get('STATIC_PATH')}${minifiedFileServerPath}`,
    sourceMap,
    minifiedFile,
    projectRoot: __dirname,
    uploadSources: true,
  });
}

/**
 * Find, upload and delete Source Maps
 */
function processSourceMaps() {
  findSourceMaps((error, files) =>
    Promise.all(files.map(uploadSourceMap))
      .then(() => {
        deleteFiles(files);
        notifyRelease();
      })
      .catch(e => {
        console.log(e);
      })
  );
}
processSourceMaps();
```
# (Insert code sample to reproduce the problem)
```
This is the Article from where I referenced code to write upload function:
https://medium.com/sovtech-insights/upload-create-react-app-source-maps-to-bugsnag-for-easier-debugging-and-delete-them-afterwards-for-c834c729506a

<!-- Error messages, if any -->
> Source mapping failed:
> A source map could not be found
> Could not find original source file and line numbers because the source map could not be downloaded from https://hostname/minifiedFileName.js.map. Ensure that your source map is accessible from our servers or upload them to us. (Note that events are not reprocessed after source maps are uploaded.)
>

**Comment by johnkiely1** [comment]
Hi @harsimerkaur,

The source URL is intended to show the minified JS file which the source map relates to and should match the path to the minified JS file shown in the stacktrace. If you contact support@bugsnag.com with details of your account we can confirm why it's not matching for your stacktraces."
