### ISSUE TITLE
Simplify uploading of create-react-app files

### ISSUE THREAD

**Issue by rhuanbarreto** [bugsnag/bugsnag-sourcemaps#62]
### Description

After some back and forth with Bugsnag support I made a script to simplify the upload of create-react-app build files to bugsnag.

This is very useful if your project runs on a closed server on an intranet.

https://gist.github.com/rhuanbarreto/eafdc8b835f7b0a438ea629084b91313

Maybe this library could incorporate some of what I did and automate the process using npx?

**Comment by mattdyoung** [comment]
Hi @rhuanbarreto 

Thanks for sharing! We're in the process of making some improvements to our tooling for uploading source maps which should support `create-react-app` much better so we'll be sure to provide an update here with the details when this is available.

**Comment by mattdyoung** [comment]
An update to say that we have now released a new source map upload tool which provides much better support for create-react-app:
https://github.com/bugsnag/bugsnag-source-maps

We've updated our documentation to recommend using the new tool for create-react-app and provided example usage:
https://docs.bugsnag.com/platforms/javascript/react/source-maps/#uploading-source-maps-recommended
https://docs.bugsnag.com/build-integrations/js/source-maps-browser/#examples
