### ISSUE TITLE
Tests, tests, tests

### ISSUE THREAD

**Issue by jmshal** [bugsnag/bugsnag-sourcemaps#9]
The module used to be no more than a simple 50 line function<sup>[[1]](https://github.com/jmshal/bugsnag-sourcemaps/blob/10a4f1fb14768a3306bfef23efdc55d0cc428aea/index.js#L15-L65)</sup>, but it's grown a bit larger than that now - so it's worth adding some tests.

**Comment by kattrali** [comment]
Hmm, is there a level of coverage that this issue needs to meet?

**Comment by jmshal** [comment]
I didn’t exactly have a number in mind, but I was hoping (probably fairly nievely) for the majority. I’m going to be working on gaining some more coverage this weekend when I get time.

**Comment by kattrali** [comment]
Cool. If you can figure out how to make/break my terrible test branch, that would be cool too!

**Comment by jmshal** [comment]
Haha, absolutely! 😛

**Comment by bengourley** [comment]
There are now unit tests and end to end tests, so I'm going to close this off!
